[package]
name = "chip8rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.8.1"
ggegui = "0.3.5"
egui = "0.22.0"
native-dialog = "0.6.4"
