[package]
name = "chip8rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.8.1"
native-dialog = "0.6.4"
thiserror = "1.0.40"
rand = "0.8.5"
