[package]
name = "chip8rs"
version = "0.1.0"
edition = "2021"

[dependencies]
native-dialog = "0.6.4"
thiserror = "1.0.40"
rand = "0.8.5"
pixels = "0.13.0"
winit = "0.28.6"
winit_input_helper = "0.14.1"
env_logger = "0.10.0"
log = "0.4.19"
phf = "0.11.2"
